const axios = require('axios');

const RD_API_URL = 'https://api.real-debrid.com/rest/1.0';

// Helper to interact with RD
async function requestRD(endpoint, token, method = 'GET', data = null) {
    try {
        const url = `${RD_API_URL}${endpoint}`;
        const headers = { Authorization: `Bearer ${token}` };

        let response;
        if (method === 'GET') {
            response = await axios.get(url, { headers });
        } else if (method === 'POST') {
            response = await axios.post(url, data, { headers });
        }
        return response.data;
    } catch (e) {
        console.error(`[RD API Error] ${endpoint}:`, e.response ? e.response.data : e.message);
        throw e;
    }
}

// 1. Check instant availability of multiple hashes
// RD allows checking multiple hashes by separating with "/"
async function checkRealDebrid(torrents, rdToken, config, hostUrl = 'http://localhost:7000') {
    if (!torrents || torrents.length === 0) return [];

    // Max 100 hashes per request usually, we slice for safety
    const hashes = torrents.map(t => t.hash).slice(0, 100);
    const hashString = hashes.join('/');

    let cachedMask = {};
    try {
        const rdCache = await requestRD(`/torrents/instantAvailability/${hashString}`, rdToken);
        // rdCache structure: { "hash1": { "rd": [ { "1": { ... }, "2": { ... } } ] }, "hash2": ... }
        Object.keys(rdCache).forEach(hash => {
            if (rdCache[hash] && rdCache[hash].rd && rdCache[hash].rd.length > 0) {
                cachedMask[hash.toLowerCase()] = true;
            }
        });
    } catch (e) {
        console.warn('Real Debrid cache check failed, falling back to all links');
    }

    // Map the torrents to Stremio Stream Objects
    const streams = [];

    for (const t of torrents) {
        const isCached = cachedMask[t.hash.toLowerCase()];

        // We skip uncached if we only want cached, but for now we'll label them
        const cacheLabel = isCached ? '⚡ RD CACHED' : '⏳ RD DOWNLOADING';

        // Return the final Stream Object
        // For Stremio, the `name` is the small block on the left (e.g. StreamAI 4K)
        // and `title` is the longer text containing details.
        const stream = {
            name: `StreamAI\n${t.quality}`,
            title: `[RD+] CACHED | ${t.provider}\n💾 ${t.size} | 👤 ${t.seeders}\nReal Debrid High-Speed Link`,
            behaviorHints: {
                bingeGroup: `StreamAI-${t.quality}`
            }
        };

        // If we configure our proxy endpoint correctly, we can point 'url' to our own server
        // so that it handles the exact un-restricting when the user clicks Play.
        // We pass the hash and the encoded token in the URL.
        const encodedToken = Buffer.from(rdToken).toString('base64');
        const proxyUrl = `${hostUrl}/proxy/rd/${encodedToken}/${t.hash}`;

        // We provide the url parameter which Stremio will GET to stream the file.
        // On that GET request, our server will talk to RD to unrestrict and redirect (302) to the media URL.
        stream.url = proxyUrl;

        streams.push(stream);
    }

    return streams;
}

// 2. Just-In-Time Unrestrict Logic (Called when User plays a stream)
async function unrestrictLink(hash, rdToken) {
    // 1. Add Magnet to RD
    const magnet = `magnet:?xt=urn:btih:${hash}`;
    const addData = new URLSearchParams();
    addData.append('magnet', magnet);
    const added = await requestRD('/torrents/addMagnet', rdToken, 'POST', addData);

    // 2. Select files (select all files for simplicity, or we could select largest video file)
    const selectData = new URLSearchParams();
    selectData.append('files', 'all');
    await requestRD(`/torrents/selectFiles/${added.id}`, rdToken, 'POST', selectData);

    // 3. Get Torrent info to find the generated download links
    const info = await requestRD(`/torrents/info/${added.id}`, rdToken);
    if (!info.links || info.links.length === 0) {
        throw new Error('No links generated by RD.');
    }

    // 4. Unrestrict the first link (usually the main video file)
    const unrestrictData = new URLSearchParams();
    unrestrictData.append('link', info.links[0]);
    const unresticted = await requestRD('/unrestrict/link', rdToken, 'POST', unrestrictData);

    return unresticted.download; // This is the final high-speed playable URL
}

module.exports = { checkRealDebrid, unrestrictLink };
